# The Energy of a Quantum Physical Two-Body System

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D

## Constants

In [15]:
# sigma = 1
# x0 = 0

#planck = 6.626e-34
#reduced_planck = planck/(2*np.pi)
#e_mass = 9.109e-31

## Discretization

In [16]:
# Length of interval
L = 20
# No. of subintervals
N = 500
# Stepsize
h = L / (N-1)

# Argument vector
xi = np.linspace(-L/2, L/2, N)

## Functions

In [17]:
def v_func(x):
    """ Returns the portential function of the quantum system """
    return x**2/2

In [18]:
def psi_func(x, *args):
    """ Returns the wave function. *args takes optional number of parameters 
    is just an implementation detail to facilitate the populate_vector function"""
    x0, sigma = args

    return np.sqrt(1/(sigma*np.sqrt(2*np.pi)))*np.exp(-(x-x0)**2/(4*sigma**2))

In [19]:
def populate_vector(func, *args):
    """ Returns a vector of the given function in N range"""
    vector = [func(xi[i], *args) for i in range(N)]
    return np.array(vector).reshape(-1, 1)

In [20]:
def finite_difference_scheme():
    """ Returns a matrix representation of a second order central finite difference scheme"""
    m = np.zeros((N,N))
    for i in range(N):
        m[i,i] = -2
        if i+1 < N:
            m[i,i+1] = 1
        if i-1 >= 0:
            m[i, i-1] = 1
    return m

In [21]:
def compute_e(x0, sigma):
    """  """
    psi_vector = populate_vector(psi_func, x0, sigma)
    
    #kinetic_constant = -reduced_planck**2/(2*e_mass) # Kan være 1 inntil videre
    h_psi = -1/2*(1/h**2)*(finite_difference_matrix @ psi_vector) + (v_vector * psi_vector)
     
    e = h*(psi_vector.T @ h_psi)  
    
    return e[0][0]

In [23]:
def finite_difference_e(x, y):
    """  """
    return (compute_e(x+h, y) - compute_e(x-h, y))/2*h

In [44]:
def gradient_step(x0, sigma):
    lr = 0.01
    # print(finite_difference_e(sigma, x0))
    new_x0 = x0 - lr*finite_difference_e(x0, sigma)
    new_sigma = sigma - lr*finite_difference_e(sigma, x0)
    return (new_x0, new_sigma)
    
    

In [45]:
def gradient_descent(x0, sigma):
    iterations = 0
    max_iterations = 2000
    precision = 1e-7
    
    #e = 
    #e_new
    
    
    while (iterations < max_iterations):
    
        x0, sigma = gradient_step(x0, sigma)
        iterations += 1
        
        
        
    return x0, sigma

## Computing the Energy

Tweake parameter(lr, x0, sigma).
Lage plot
Sette stoppkriterier.


fasit
x0 = 0
sigma = 1/sqrt(2)
e = 0.5

In [46]:
# Initializing vectors
v_vector = populate_vector(v_func)
finite_difference_matrix = finite_difference_scheme()
print(finite_difference_matrix)    
    

[[-2.  1.  0. ...  0.  0.  0.]
 [ 1. -2.  1. ...  0.  0.  0.]
 [ 0.  1. -2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -2.  1.  0.]
 [ 0.  0.  0. ...  1. -2.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]]


In [47]:
x0 = 0.1
sigma = 0.8

e = compute_e(x0, sigma)
print(f"Energy at guess {e}")
new_x0, new_sigma = gradient_descent(x0, sigma) 
print(new_x0, new_sigma)
print(compute_e(new_x0, new_sigma))

Energy at guess 0.5202818631885944
0.09683819984156898 0.7747055987325618
0.5130131137419279


In [ ]:
# Forsøk på plotting:

X = np.arange(-5, 5, 0.1)
Y = np.arange(0.5, 2, ((2-0.5)/len(X)))

E = np.zeros((len(X), len(Y)))

for i,x in enumerate(X):
    for j,y in enumerate(Y):
        E[i][j] = compute_e(x, y)

X, Y = np.meshgrid(X, Y)

print(X.shape, Y.shape, E.shape)

fig = plt.figure()

ax = Axes3D(fig)
ax.plot_surface(X, Y, E,  cmap=cm.viridis)

plt.show()

